# CMake toolchain for the Windows cross build (windows/inside.sh):
#   cmake -DCMAKE_TOOLCHAIN_FILE=windows/toolchain.cmake -DWIN_ARCH=x86_64|aarch64
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 10.0)
if(WIN_ARCH STREQUAL "aarch64")
  set(CMAKE_SYSTEM_PROCESSOR ARM64)
else()
  set(CMAKE_SYSTEM_PROCESSOR AMD64)
endif()
set(CMAKE_C_COMPILER   /opt/wincross/bin/${WIN_ARCH}-windows-clang)
set(CMAKE_CXX_COMPILER /opt/wincross/bin/${WIN_ARCH}-windows-clang++)
set(CMAKE_RC_COMPILER  /usr/lib/llvm-19/bin/llvm-rc)
set(CMAKE_AR           /usr/lib/llvm-19/bin/llvm-ar)
set(CMAKE_RANLIB       /usr/lib/llvm-19/bin/llvm-ranlib)
set(CMAKE_MT           /usr/lib/llvm-19/bin/llvm-mt)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_INSTALL_PREFIX})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
